name: filesystem_picker
description: FileSystem file or folder picker dialog. Allows the user to browse the file system and pick a folder or file.
version: 4.1.0
author: Andy Chentsov <chentsov@gmail.com>
homepage: https://github.com/andyduke/filesystem_picker/tree/master/package
repository: https://github.com/andyduke/filesystem_picker
issue_tracker: https://github.com/andyduke/filesystem_picker/issues

screenshots:
  - description: "Types of pickers: full screen, dialog, bottom sheet"
    path: screenshots/types_of_picker.png
  - description: Picker customization
    path: screenshots/picker_customization.png

topics:
  - picker
  - files
  - file-selection
  - file-selector
  - ui

environment:
  flutter: ">=3.0.0"
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
