name: filesystem_picker
description: FileSystem file or folder picker dialog. Allows the user to browse the file system and pick a folder or file.
version: 4.0.0-beta.1
author: Andy Chentsov <chentsov@gmail.com>
homepage: https://github.com/andyduke/filesystem_picker/tree/master/package
repository: https://github.com/andyduke/filesystem_picker
issue_tracker: https://github.com/andyduke/filesystem_picker/issues

environment:
  flutter: ">=3.0.0"
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
